# Generated by Django 6.0.3 on 2026-03-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('DRAMA', 'Drama')], default='INFO', max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='agents.agent')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='worlds.world')),
            ],
            options={
                'ordering': ['-tick', '-created_at'],
            },
        ),
    ]
