# Generated by Django 6.0.3 on 2026-03-17 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('AGGRESSIVE_RAIDER', 'Aggressive Raider'), ('ECONOMIC_TRADER', 'Economic Trader'), ('DIPLOMAT', 'Diplomat'), ('EXPLORER', 'Explorer'), ('OPPORTUNIST', 'Opportunist')], max_length=50)),
                ('intelligence_tier', models.CharField(choices=[('TIER_1', 'Tier 1 (Basic)'), ('TIER_2', 'Tier 2 (Advanced)'), ('TIER_3', 'Tier 3 (Elite)')], default='TIER_1', max_length=20)),
                ('energy', models.FloatField(default=100.0)),
                ('hunger', models.FloatField(default=0.0)),
                ('wealth', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('reputation', models.IntegerField(default=0)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ACTIVE', 'Active'), ('DEAD', 'Dead'), ('BANKRUPT', 'Bankrupt')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spawned_at', models.DateTimeField(blank=True, null=True)),
                ('died_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='worlds.world')),
            ],
        ),
        migrations.CreateModel(
            name='SpawnQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spawn_tick', models.PositiveIntegerField(help_text='The tick at which the agent should spawn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='agents.agent')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawn_queue', to='worlds.world')),
            ],
            options={
                'ordering': ['spawn_tick', 'created_at'],
            },
        ),
    ]
