# Generated by Django 6.0.3 on 2026-03-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('CREATION', 'Creation'), ('ENTRY', 'Entry Window'), ('ACTIVE', 'Active Simulation'), ('ENDGAME', 'Endgame Pressure'), ('SETTLEMENT', 'Settlement'), ('ARCHIVED', 'Archived')], default='CREATION', max_length=20)),
                ('tick_interval', models.PositiveIntegerField(default=60, help_text='In seconds')),
                ('max_agents', models.PositiveIntegerField(default=50)),
                ('current_tick', models.PositiveIntegerField(default=0)),
                ('entry_window_close_tick', models.PositiveIntegerField(default=144)),
                ('map_size_x', models.PositiveIntegerField(default=100)),
                ('map_size_y', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('resource_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('respawn_tick', models.PositiveIntegerField(blank=True, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_nodes', to='worlds.world')),
            ],
        ),
    ]
